version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
  - master
  except:
  - gh-pages
image: Visual Studio 2019
install:
- cmd: mvn --version
- cmd: java -version
build_script:
- mvn clean package -B -Dmaven.test.skip=true
test_script:
- mvn clean install --batch-mode -Pqulice
cache:
- C:\maven\
- C:\Users\appveyor\.m2
artifacts:
- path: target/ExtraHardMode.jar
  name: ExtraHardMode
